---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-helm
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/infrastructure/components/cert-manager/helmrelease
  prune: true
  sourceRef:
    kind: GitRepository
    name: ubersystem-eks
