### Database
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${db_primary:=database}
  namespace: ${eventname}
spec:
  description: "${eventname} Postgres Cluster"
  instances: ${cnpg_replicas:=3}
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  postgresql:
    parameters:
      pg_stat_statements.max: "100000"
      pg_stat_statements.track: all
      log_statement: all
  storage:
    size: ${cnpg_db_size:=10Gi}
    storageClass: ebs-sc

  bootstrap:
    recovery:
      source: primary-cluster-backup 
      recoveryTarget:
        targetTimeline: "latest"

  externalClusters:
    - name: primary-cluster-backup
      barmanObjectStore:
        serverName: database
        destinationPath: "s3://${db_backup_bucket}/${eventname}${cnpg_read_generation}"
        s3Credentials:
          inheritFromIAMRole: true
        wal:
          maxParallel: 8

  backup:
    barmanObjectStore:
      destinationPath: "s3://${db_backup_bucket}/${eventname}${cnpg_write_generation}"
      s3Credentials:
        inheritFromIAMRole: true
      wal:
        compression: gzip
        maxParallel: 2
      data:
        compression: gzip
    retentionPolicy: ${cnpg_db_retention:=30d}

---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-pool
  namespace: ${eventname}
spec:
  cluster:
    name: ${db_primary:=database}
  instances: 1
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "100"

---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-pool-ro
  namespace: ${eventname}
spec:
  cluster:
    name: ${db_primary:=database}
  instances: 1
  type: ro
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "100"

---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: database-backup
  namespace: ${eventname}
spec:
  method: barmanObjectStore
  cluster:
    name: ${db_primary:=database}

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: database-backup
  namespace: ${eventname}
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: ${db_primary:=database}
