---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
spec:
  sourceRef:
    kind: GitRepository
    name: ubersystem
  path: ./flux/infrastructure
  prune: true
  interval: 10m
  dependsOn:
  - name: flux-system
