---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/helm
  prune: true
  interval: 10m
  postBuild:
    substitute:
      cert_arn: arn:aws:acm:us-east-1:278110951434:certificate/7720b73f-77df-471b-9a75-701f6581b526
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/crds
  prune: true
  interval: 10m
  postBuild:
    substitute:
      efs_filesystem: fs-01f9693f767949e05
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure
  prune: true
  interval: 10m
  dependsOn:
    - name: crds
  postBuild:
    substitute:
      efs_filesystem: fs-01f9693f767949e05
      db_backup_bucket: ubersystem-backups-production/cnpg