#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: ubersystem-super2026
#  namespace: flux-system
#spec:
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./flux/ubersystem
#  prune: true
#  interval: 10m
#  targetNamespace: default
#  postBuild:
#    substitute:
#      eventname: super
#      eventyear: "2026"
#      environment: prod
#      hostname: super2026.reg.magfest.org
#      container: ghcr.io/magfest/magprime:main
#      webreplicas: "1"
#      webram: "128Mi"
#      webcpu: "64m"
#      celeryram: "128Mi"
#      celerycpu: "64m"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-super2025
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: default
  postBuild:
    substitute:
      eventname: super
      eventyear: "2025"
      environment: prod
      hostname: super2025.reg.magfest.org
      container: ghcr.io/magfest/magprime:main
      webreplicas: "1"
      webram: "128Mi"
      webcpu: "64m"
      celeryram: "128Mi"
      celerycpu: "64m"
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: ubersystem-west2025
#  namespace: flux-system
#spec:
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./flux/ubersystem
#  prune: true
#  interval: 10m
#  targetNamespace: default
#  postBuild:
#    substitute:
#      eventname: west
#      eventyear: "2025"
#      environment: prod
#      hostname: west2025.reg.magfest.org
#      container: ghcr.io/magfest/magwest:west2025
#      webreplicas: "1"
#      webram: "128Mi"
#      webcpu: "64m"
#      celeryram: "128Mi"
#      celerycpu: "64m"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-west2024
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: default
  postBuild:
    substitute:
      eventname: west
      eventyear: "2024"
      environment: prod
      hostname: west2024.reg.magfest.org
      container: ghcr.io/magfest/magwest:west2024
      webreplicas: "1"
      webram: "128Mi"
      webcpu: "64m"
      celeryram: "128Mi"
      celerycpu: "64m"
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: ubersystem-stock2025
#  namespace: flux-system
#spec:
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./flux/ubersystem
#  prune: true
#  interval: 10m
#  targetNamespace: default
#  postBuild:
#    substitute:
#      eventname: stock
#      eventyear: "2025"
#      environment: prod
#      hostname: stock2025.reg.magfest.org
#      container: ghcr.io/magfest/magstock:stock2025
#      webreplicas: "1"
#      webram: "128Mi"
#      webcpu: "64m"
#      celeryram: "128Mi"
#      celerycpu: "64m"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-stock2024
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: default
  postBuild:
    substitute:
      eventname: stock
      eventyear: "2024"
      environment: prod
      hostname: stock2024.reg.magfest.org
      container: ghcr.io/magfest/magstock:stock2024
      webreplicas: "1"
      webram: "128Mi"
      webcpu: "64m"
      celeryram: "128Mi"
      celerycpu: "64m"
