---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: Ubersystem-EKS
spec:
  url: https://github.com/magfest/Ubersystem-EKS.git
  interval: 1m
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: Ubersystem-EKS
  path: ./flux/flux-system
  prune: true
  interval: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
spec:
  sourceRef:
    kind: GitRepository
    name: Ubersystem-EKS
  path: ./flux/infrastructure
  prune: true
  interval: 10m
  dependsOn:
  - name: flux-system
