---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-super
spec:
  sourceRef:
    kind: GitRepository
    name: Ubersystem-EKS
  path: ./flux/ubersystem
  prune: true
  interval: 1m
  targetNamespace: default
  dependsOn:
  - name: flux-system
  - name: infrastructure
  postBuild:
    substitute:
      eventname: super
      hostname: super.dev.magevent.net
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-west
spec:
  sourceRef:
    kind: GitRepository
    name: Ubersystem-EKS
  path: ./flux/ubersystem
  prune: true
  interval: 1m
  targetNamespace: default
  dependsOn:
  - name: flux-system
  - name: infrastructure
  postBuild:
    substitute:
      eventname: west
      hostname: west.dev.magevent.net