---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-super
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: default
  dependsOn:
  - name: crds
  postBuild:
    substitute:
      eventname: super
      eventyear: "2026"
      environment: staging
      hostname: super-test.dev.magevent.net
      container: ghcr.io/magfest/magprime:main
      webreplicas: "5"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-west
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: default
  dependsOn:
  - name: crds
  postBuild:
    substitute:
      eventname: west
      eventyear: "2025"
      environment: staging
      hostname: west-test.dev.magevent.net
      container: ghcr.io/magfest/magwest:west2025
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-stock
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: default
  dependsOn:
  - name: crds
  postBuild:
    substitute:
      eventname: stock
      eventyear: "2025"
      environment: staging
      hostname: stock-test.dev.magevent.net
      container: ghcr.io/magfest/magstock:stock2025