---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-super
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: default
  postBuild:
    substitute:
      eventname: super
      eventyear: "2026"
      environment: staging
      hostname: super-test.dev.magevent.net
      container: ghcr.io/magfest/magprime:main
      webreplicas: "1"
      webram: "128Mi"
      webcpu: "64m"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-west
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: default
  postBuild:
    substitute:
      eventname: west
      eventyear: "2025"
      environment: staging
      hostname: west-test.dev.magevent.net
      container: ghcr.io/magfest/magwest:west2025
      webram: "128Mi"
      webcpu: "64m"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-stock
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: default
  postBuild:
    substitute:
      eventname: stock
      eventyear: "2025"
      environment: staging
      hostname: stock-test.dev.magevent.net
      container: ghcr.io/magfest/magstock:stock2025
      webram: "128Mi"
      webcpu: "64m"