---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-super
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 1m
  targetNamespace: default
  dependsOn:
  - name: crds
  postBuild:
    substitute:
      eventname: super
      hostname: super.dev.magevent.net
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-west
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 1m
  targetNamespace: default
  dependsOn:
  - name: crds
  postBuild:
    substitute:
      eventname: west
      hostname: west.dev.magevent.net