---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-super
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: super2026
  postBuild:
    substitute:
      eventname: super2026
      hostname: super.dev.magevent.net
      container: ghcr.io/magfest/magprime:main
      webreplicas: "1"
      webram: "128Mi"
      webcpu: "64m"
      celeryram: "128Mi"
      celerycpu: "64m"
      config_paths: "uber_config/environments/staging uber_config/events/super/2026/staging"
      db_backup_bucket: ubersystem-backups-staging
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-west
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: west2025
  postBuild:
    substitute:
      eventname: west2025
      hostname: west.dev.magevent.net
      container: ghcr.io/magfest/magwest:west2025
      webram: "128Mi"
      webcpu: "64m"
      celeryram: "128Mi"
      celerycpu: "64m"
      config_paths: "uber_config/environments/staging uber_config/events/west/2025/staging"
      db_backup_bucket: ubersystem-backups-staging
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubersystem-stock
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/ubersystem
  prune: true
  interval: 10m
  targetNamespace: stock2025
  postBuild:
    substitute:
      eventname: stock2025
      hostname: stock.dev.magevent.net
      container: ghcr.io/magfest/magstock:stock2025
      webram: "128Mi"
      webcpu: "64m"
      celeryram: "128Mi"
      celerycpu: "64m"
      config_paths: "uber_config/environments/staging uber_config/events/stock/2025/staging"
      db_backup_bucket: ubersystem-backups-staging