---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-uploads
  namespace: default
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ubersystem-test
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    app: web

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks.dev.magevent.net
  namespace: default
spec:
  rules:
  - host: eks.dev.magevent.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ubersystem-test
            port:
              number: 80
  ingressClassName: nginx

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ubersystem
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: ubersystem
      volumes:
      - name: web-uploads
        persistentVolumeClaim:
          claimName: web-uploads
      terminationGracePeriodSeconds: 5
      containers:
      - name: web
        image: "ghcr.io/magfest/magprime:main"
        ports:
        - containerPort: 80
        env:
        - name: "DB_CONNECTION_STRING"
          valueFrom: 
            secretKeyRef:
              name: postgres-app
              key: uri
        - name: "LOG_CONFIG"
          value: "true"
        - name: "CONFIG_REPO"
          value: "https://github.com/magfest/terraform-aws-magfest.git"
        - name: "CONFIG_PATHS"
          value: "uber_config/environments/staging uber_config/events/super/2026/staging"
        - name: "uber_cherrypy_server_socket_port"
          value: "80"
        - name: "uber_cherrypy_server_socket_host"
          value: "0.0.0.0"
        - name: "uber_cherrypy_server_socket_timeout"
          value: "1"
        - name: "uber_cherrypy_tools_sessions_host"
          value: "redis"
        - name: "uber_cherrypy_tools_sessions_prefix"
          value: "uber"
        - name: "uber_cherrypy_tools_sessions_storage_type"
          value: "redis"
        - name: "uber_redis_host"
          value: "redis"
        - name: "uber_secret_broker_url"
          value: "amqp://celery:celery@rabbitmq:5672/uber"
        - name: "uber_hostname"
          value: "localhost"
        - name: "uber_dev_box"
          value: "True"
        volumeMounts:
        - mountPath: "/app/plugins/uber/uploaded_files"
          name: web-uploads

---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-admin
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: create-admin
        image: quay.io/curl/curl:latest
        command: ["curl", "--fail-with-body", "http://ubersystem-test.default.svc.cluster.local:80/accounts/insert_test_admin"]
      restartPolicy: Never
  backoffLimit: 4

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: celery-beats
  namespace: default
  labels:
    app: celery-beats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beats
  template:
    metadata:
      labels:
        app: celery-beats
    spec:
      volumes:
      - name: web-uploads
        persistentVolumeClaim:
          claimName: web-uploads
      terminationGracePeriodSeconds: 5
      containers:
      - name: celery-beats
        image: "ghcr.io/magfest/magprime:main"
        args: ["celery-beat"]
        env:
        - name: "DB_CONNECTION_STRING"
          valueFrom: 
            secretKeyRef:
              name: postgres-app
              key: uri
        - name: "LOG_CONFIG"
          value: "true"
        - name: "CONFIG_REPO"
          value: "https://github.com/magfest/terraform-aws-magfest.git"
        - name: "CONFIG_PATHS"
          value: "uber_config/environments/staging uber_config/events/super/2026/staging"
        - name: "uber_cherrypy_server_socket_port"
          value: "80"
        - name: "uber_cherrypy_server_socket_host"
          value: "0.0.0.0"
        - name: "uber_cherrypy_server_socket_timeout"
          value: "1"
        - name: "uber_cherrypy_tools_sessions_host"
          value: "redis"
        - name: "uber_cherrypy_tools_sessions_prefix"
          value: "uber"
        - name: "uber_cherrypy_tools_sessions_storage_type"
          value: "redis"
        - name: "uber_redis_host"
          value: "redis"
        - name: "uber_secret_broker_url"
          value: "amqp://celery:celery@rabbitmq:5672/uber"
        - name: "uber_hostname"
          value: "localhost"
        - name: "uber_dev_box"
          value: "True"
        volumeMounts:
        - mountPath: "/app/plugins/uber/uploaded_files"
          name: web-uploads

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: default
  labels:
    app: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      volumes:
      - name: web-uploads
        persistentVolumeClaim:
          claimName: web-uploads
      terminationGracePeriodSeconds: 5
      containers:
      - name: celery-worker
        image: "ghcr.io/magfest/magprime:main"
        args: ["celery-worker"]
        env:
        - name: "DB_CONNECTION_STRING"
          valueFrom: 
            secretKeyRef:
              name: postgres-app
              key: uri
        - name: "LOG_CONFIG"
          value: "true"
        - name: "CONFIG_REPO"
          value: "https://github.com/magfest/terraform-aws-magfest.git"
        - name: "CONFIG_PATHS"
          value: "uber_config/environments/staging uber_config/events/super/2026/staging"
        - name: "uber_cherrypy_server_socket_port"
          value: "80"
        - name: "uber_cherrypy_server_socket_host"
          value: "0.0.0.0"
        - name: "uber_cherrypy_server_socket_timeout"
          value: "1"
        - name: "uber_cherrypy_tools_sessions_host"
          value: "redis"
        - name: "uber_cherrypy_tools_sessions_prefix"
          value: "uber"
        - name: "uber_cherrypy_tools_sessions_storage_type"
          value: "redis"
        - name: "uber_redis_host"
          value: "redis"
        - name: "uber_secret_broker_url"
          value: "amqp://celery:celery@rabbitmq:5672/uber"
        - name: "uber_hostname"
          value: "localhost"
        - name: "uber_dev_box"
          value: "True"
        volumeMounts:
        - mountPath: "/app/plugins/uber/uploaded_files"
          name: web-uploads
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ubersystem-eks
  namespace: default
spec:
  name: ubersystem-eks
  owner: ubersystem-eks
  cluster:
    name: ubersystem