apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis.yaml

patches:
- patch: &env_patch |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: uber_cherrypy_tools_sessions_host
        value: redis
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: uber_cherrypy_tools_sessions_prefix
        value: uber
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: uber_cherrypy_tools_sessions_storage_type
        value: redis
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: uber_redis_host
        value: redis
  target:
    kind: Deployment
    name: web

- patch: *env_patch
  target:
    kind: Deployment
    name: celery-beats

- patch: *env_patch
  target:
    kind: Deployment
    name: celery-worker