apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rabbitmq.yaml

patches:
- patch: &env_patch |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: uber_secret_broker_url
        value: amqp://celery:celery@rabbitmq:5672/uber
  target:
    kind: Deployment
    name: web

- patch: *env_patch
  target:
    kind: Deployment
    name: celery-beats

- patch: *env_patch
  target:
    kind: Deployment
    name: celery-worker