---
apiVersion: v1
kind: Service
metadata:
  name: ${eventname}-rabbitmq
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: rabbitmq
  selector:
    app: ${eventname}-rabbitmq

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${eventname}-rabbitmq
  namespace: default
  labels:
    app: ${eventname}-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${eventname}-rabbitmq
  template:
    metadata:
      labels:
        app: ${eventname}-rabbitmq
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: rabbitmq
        image: "rabbitmq:alpine"
        ports:
        - containerPort: 5672
        env:
        - name: "RABBITMQ_DEFAULT_USER"
          value: "celery"
        - name: "RABBITMQ_DEFAULT_PASS"
          value: "celery"
        - name: "RABBITMQ_DEFAULT_VHOST"
          value: "uber"

---
apiVersion: v1
kind: Service
metadata:
  name: ${eventname}-flower
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 5555
      targetPort: 5555
      protocol: TCP
      name: flower
  selector:
    app: ${eventname}-flower

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${eventname}-flower
  namespace: default
  labels:
    app: ${eventname}-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${eventname}-flower
  template:
    metadata:
      labels:
        app: ${eventname}-flower
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: flower
        image: "mher/flower:2.0"
        ports:
        - containerPort: 5555
        env:
        - name: "CELERY_BROKER_URL"
          value: "amqp://celery:celery@rabbitmq:5672/uber"
        - name: "FLOWER_PORT"
          value: "5555"