---
apiVersion: v1
kind: Service
metadata:
  name: ${eventname}-redis
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: ${eventname}-redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${eventname}-redis
  namespace: default
  labels:
    app: ${eventname}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${eventname}-redis
  template:
    metadata:
      labels:
        app: ${eventname}-redis
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: redis
        image: "redis"
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128"
            cpu: "50m"
          limits:
            memory: "256"
            cpu: "200m"