---
apiVersion: v1
kind: Namespace
metadata:
  name: ${eventname}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ${eventname}
  labels:
    app: web
spec:
  replicas: ${webreplicas:=1}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: ubersystem-email
      volumes:
      - name: uploaded-files
        persistentVolumeClaim:
          claimName: uploaded-files
      - name: config-key
        projected:
          sources:
          - secret:
              name: flux-system
              items:
                - key: identity
                  path: id_rsa
      terminationGracePeriodSeconds: 5
      containers:
      - name: web
        image: "${container}"
        imagePullPolicy: Always
        livenessProbe:
          timeoutSeconds: 10
          periodSeconds: 60
          httpGet:
            path: /landing/
            port: 80
        readinessProbe:
          timeoutSeconds: 10
          periodSeconds: 60
          httpGet:
            path: /devtools/health
            port: 80
        startupProbe:
          initialDelaySeconds: 20
          failureThreshold: 20
          httpGet:
            path: /devtools/health
            port: 80
        resources:
          requests:
            memory: ${webram:=128Mi}
            cpu: ${webcpu:=64m}
          limits:
            memory: ${webram_limit:=1024Mi}
            cpu: ${webcpu_limit:=1000m}
        ports:
        - containerPort: 80
        env:
        - name: LOG_CONFIG
          value: "true"
        - name: "CONFIG_REPO"
          value: ${config_repo:=https://github.com/magfest/RAMS-Config.git}
        - name: "CONFIG_PATHS"
          value: "${config_paths}"
        - name: "uber_cherrypy_server_socket_port"
          value: "80"
        - name: "uber_cherrypy_server_socket_host"
          value: "0.0.0.0"
        - name: "uber_cherrypy_server_thread_pool"
          value: "10"
        - name: "uber_cherrypy_server_socket_timeout"
          value: "1"
        - name: "uber_hostname"
          value: "localhost"
        - name: "UBERSYSTEM_SECRETS"
          valueFrom:
            secretKeyRef:
              name: uber-secrets
              key: secrets
        volumeMounts:
        - mountPath: "/app/uploaded_files"
          name: uploaded-files
          subPath: ${eventname}
        - name: config-key
          mountPath: /root/.ssh
          readOnly: true
          optional: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beats
  namespace: ${eventname}
  labels:
    app: celery-beats
spec:
  replicas: ${beatsreplicas:=1}
  selector:
    matchLabels:
      app: celery-beats
  template:
    metadata:
      labels:
        app: celery-beats
    spec:
      volumes:
      - name: uploaded-files
        persistentVolumeClaim:
          claimName: uploaded-files
      - name: config-key
        projected:
          sources:
          - secret:
              name: flux-system
              items:
                - key: identity
                  path: id_rsa
      terminationGracePeriodSeconds: 5
      containers:
      - name: celery-beats
        image: "${container}"
        imagePullPolicy: Always
        args: ["celery-beat"]
        resources:
          requests:
            memory: ${beatsram:=256Mi}
            cpu: ${beatscpu:=500m}
          limits:
            memory: ${beatsram_limit:=512Mi}
            cpu: ${beatscpu_limit:=500m}
        env:
        - name: LOG_CONFIG
          value: "true"
        - name: "CONFIG_REPO"
          value: ${config_repo:=https://github.com/magfest/RAMS-Config.git}
        - name: "CONFIG_PATHS"
          value: "${config_paths}"
        - name: "uber_cherrypy_server_socket_port"
          value: "80"
        - name: "uber_cherrypy_server_socket_host"
          value: "0.0.0.0"
        - name: "uber_cherrypy_server_thread_pool"
          value: "10"
        - name: "uber_cherrypy_server_socket_timeout"
          value: "1"
        - name: "uber_hostname"
          value: "localhost"
        - name: "UBERSYSTEM_SECRETS"
          valueFrom:
            secretKeyRef:
              name: uber-secrets
              key: secrets
        volumeMounts:
        - mountPath: "/app/uploaded_files"
          name: uploaded-files
          subPath: ${eventname}
        - name: config-key
          mountPath: /root/.ssh
          readOnly: true
          optional: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: ${eventname}
  labels:
    app: celery-worker
spec:
  replicas: ${celeryreplicas:=1}
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      serviceAccountName: ubersystem-email
      volumes:
      - name: uploaded-files
        persistentVolumeClaim:
          claimName: uploaded-files
      - name: config-key
        projected:
          sources:
          - secret:
              name: flux-system
              items:
                - key: identity
                  path: id_rsa
      terminationGracePeriodSeconds: 5
      containers:
      - name: celery-worker
        image: "${container}"
        imagePullPolicy: Always
        args: ["celery-worker"]
        resources:
          requests:
            memory: ${celeryram:=128Mi}
            cpu: ${celerycpu:=64m}
          limits:
            memory: ${celeryram_limit:=1024Mi}
            cpu: ${celerycpu_limit:=1000m}
        env:
        - name: LOG_CONFIG
          value: "true"
        - name: "CONFIG_REPO"
          value: ${config_repo:=https://github.com/magfest/RAMS-Config.git}
        - name: "CONFIG_PATHS"
          value: "${config_paths}"
        - name: "uber_cherrypy_server_socket_port"
          value: "80"
        - name: "uber_cherrypy_server_socket_host"
          value: "0.0.0.0"
        - name: "uber_cherrypy_server_thread_pool"
          value: "10"
        - name: "uber_cherrypy_server_socket_timeout"
          value: "1"
        - name: "uber_hostname"
          value: "localhost"
        - name: "UBERSYSTEM_SECRETS"
          valueFrom:
            secretKeyRef:
              name: uber-secrets
              key: secrets
        volumeMounts:
        - mountPath: "/app/uploaded_files"
          name: uploaded-files
          subPath: ${eventname}
        - name: config-key
          mountPath: /root/.ssh
          readOnly: true
          optional: true

---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-admin
  namespace: ${eventname}
spec:
  template:
    spec:
      containers:
      - name: create-admin
        image: quay.io/curl/curl:latest
        command: ["curl", "--fail-with-body", "http://web:80/accounts/insert_test_admin"]
      restartPolicy: Never
  backoffLimit: 4
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0