---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploaded-files
  namespace: ${eventname}
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: uploaded-files-${eventname}
  resources:
    requests:
      storage: ${upload_storage_size:=20Gi}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploaded-files-${eventname}
spec:
  storageClassName: efs-sc
  claimRef:
    name: uploaded-files
    namespace: ${eventname}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  capacity:
    storage: ${upload_storage_size:=20Gi}
  csi:
    driver: efs.csi.aws.com
    volumeAttributes:
      path: /
    volumeHandle: ${efs_filesystem}