---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-helm
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/infrastructure/components/cnpg-operator/helmrelease
  prune: true
  sourceRef:
    kind: GitRepository
    name: ubersystem-eks
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-catalog
  namespace: flux-system
spec:
  dependsOn:
    - name: cnpg-helm

  interval: 10m
  path: ./flux/infrastructure/components/cnpg-operator/catalog
  prune: true
  sourceRef:
    kind: GitRepository
    name: ubersystem-eks