---
name: Pulumi Staging
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  pulumi_preview:
    environment: staging
    name: Preview Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: pip install -r platform/requirements.txt
      - name: Pulumi Preview
        id: preview
        uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: organization/staging
          cloud-url: ${{ secrets.PULUMI_BUCKET }}
          work-dir: platform
          comment-on-pr: true
          comment-on-summary: true
          color: always
          plan: /tmp/plan.json
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      - run: echo has_changes=$(jq '.resourcePlans | map(.steps[0] == "same") | all | not' < /tmp/plan.json) >> "$GITHUB_OUTPUT"

  update_staging:
    environment: staging
    name: Update Staging
    runs-on: ubuntu-latest
    needs: pulumi_preview
    if: needs.pulumi_preview.outputs.has_changes == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: pip install -r platform/requirements.txt
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: organization/staging
          cloud-url: ${{ secrets.PULUMI_BUCKET }}
          work-dir: platform
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
